apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: books.nickiness.com
spec:
  secretName: books.nickiness.com
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - "books.nickiness.com"
