---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubooquity
spec:
  rules:
  - host: books.nickiness.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ubooquity
            port:
              number: 2202
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: ubooquity
            port:
              number: 2203
      - path: /ubooquity/admin
        pathType: Prefix
        backend:
          service:
            name: ubooquity
            port:
              number: 2203
